from app.schemas.fleet import Fleet, Ship, Position


def get_initial_fleet() -> Fleet:
    return Fleet(
        ships=[
            Ship(
                id="MV-1",
                name="Aurora",
                position=Position(lat=26.55, lng=56.20),
                speed_knots=14,
                heading=105,
                destination="MCT-1",
                fuel_tons=6800,
                cargo="crude oil",
            ),
            Ship(
                id="MV-2",
                name="Borealis",
                position=Position(lat=25.50, lng=57.20),
                speed_knots=19,
                heading=270,
                destination="DXB-1",
                fuel_tons=5400,
                cargo="containers",
            ),
            Ship(
                id="MV-3",
                name="Cygnus",
                position=Position(lat=25.70, lng=53.00),
                speed_knots=16,
                heading=95,
                destination="MCT-1",
                fuel_tons=7200,
                cargo="LNG",
            ),
            Ship(
                id="MV-4",
                name="Dragon",
                position=Position(lat=26.40, lng=56.00),
                speed_knots=13,
                heading=110,
                destination="SOH-1",
                fuel_tons=5800,
                cargo="bulk grain",
            ),
            Ship(
                id="MV-5",
                name="Emerald",
                position=Position(lat=27.50, lng=51.20),
                speed_knots=12,
                heading=165,
                destination="DOH-1",
                fuel_tons=8200,
                cargo="crude oil",
            ),
            Ship(
                id="MV-6",
                name="Falcon",
                position=Position(lat=25.40, lng=54.53),
                speed_knots=22,
                heading=280,
                destination="DOH-1",
                fuel_tons=4100,
                cargo="containers",
            ),
            Ship(
                id="MV-7",
                name="Gharial",
                position=Position(lat=26.50, lng=53.50),
                speed_knots=14,
                heading=270,
                destination="KWT-1",
                fuel_tons=750,
                cargo="crude oil",
            ),
            Ship(
                id="MV-8",
                name="Halcyon",
                position=Position(lat=24.93, lng=56.94),
                speed_knots=19,
                heading=250,
                destination="DMM-1",
                fuel_tons=5200,
                cargo="automobiles",
            ),
            Ship(
                id="MV-9",
                name="Iris",
                position=Position(lat=28.20, lng=50.30),
                speed_knots=13,
                heading=175,
                destination="BAH-1",
                fuel_tons=7800,
                cargo="crude oil",
            ),
            Ship(
                id="MV-10",
                name="Jade",
                position=Position(lat=25.02, lng=57.96),
                speed_knots=20,
                heading=285,
                destination="BND-1",
                fuel_tons=6300,
                cargo="containers",
            ),
            Ship(
                id="MV-11",
                name="Kite",
                position=Position(lat=25.64, lng=52.18),
                speed_knots=18,
                heading=95,
                destination="MCT-1",
                fuel_tons=7600,
                cargo="LNG",
            ),
            Ship(
                id="MV-12",
                name="Lotus",
                position=Position(lat=29.10, lng=48.80),
                speed_knots=12,
                heading=145,
                destination="SOH-1",
                fuel_tons=8500,
                cargo="crude oil",
            ),
            Ship(
                id="MV-13",
                name="Mirage",
                position=Position(lat=24.60, lng=57.30),
                speed_knots=21,
                heading=320,
                destination="BAH-1",
                fuel_tons=5900,
                cargo="containers",
            ),
            Ship(
                id="MV-14",
                name="Nova",
                position=Position(lat=24.12, lng=58.43),
                speed_knots=11,
                heading=290,
                destination="DOH-1",
                fuel_tons=4600,
                cargo="bulk cement",
            ),
            Ship(
                id="MV-15",
                name="Orca",
                position=Position(lat=26.34, lng=55.91),
                speed_knots=13,
                heading=215,
                destination="MCT-1",
                fuel_tons=7100,
                cargo="crude oil",
            ),
        ]
    )